// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.region.update.updated", 1693039219);
user_pref("browser.search.region", "TN");
user_pref("browser.theme.dark-toolbar-theme", false);
user_pref("calendar.timezone.local", "Europe/Helsinki");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 33);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20220628000715");
user_pref("extensions.lastAppVersion", "91.11.0");
user_pref("extensions.lastPlatformVersion", "91.11.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"default-theme@mozilla.org\":\"822fe427-c91d-4a95-8584-c64516f06081\",\"google@search.mozilla.org\":\"c0774336-c6a9-43ae-9184-07827616200e\",\"ddg@search.mozilla.org\":\"b83d2cc1-5193-4983-aea2-0367f26b8582\",\"amazondotcom@search.mozilla.org\":\"a6016635-2501-4a7b-8139-0e6da0d6d3dc\",\"wikipedia@search.mozilla.org\":\"c27d9b54-c052-4dbc-a229-ab9b4aeee0ac\",\"bing@search.mozilla.org\":\"55873eca-5b3a-493b-a298-31d8af07e8ec\"}");
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.ui-rdf.version", 32);
user_pref("mailnews.database.global.datastore.id", "21fc5425-363e-4155-acfe-be548324324");
user_pref("mailnews.headers.extraAddonHeaders", "autocrypt openpgp");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "91.11.0");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.trr.blocklist_cleanup_done", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("toolkit.telemetry.cachedClientID", "4ec03722-29e5-497c-a85d-60e2e716022b");
user_pref("toolkit.telemetry.previousBuildID", "20220628000715");
